# Generated by Django 2.2.6 on 2022-01-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('good_id', models.IntegerField(verbose_name='商品id')),
                ('num', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('good_code', models.CharField(max_length=30, unique=True, verbose_name='物资编码')),
                ('good_name', models.CharField(max_length=50, verbose_name='物资名称')),
                ('good_type_id', models.IntegerField(verbose_name='物资类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='参考价值')),
                ('pics', models.TextField(verbose_name='商品图片')),
                ('introduce', models.TextField(verbose_name='商品介绍')),
                ('remark', models.CharField(max_length=255, verbose_name='商品备注')),
                ('specifications', models.TextField(verbose_name='规格参数')),
                ('status', models.BooleanField(choices=[(0, '已下架'), (1, '正常')], default=1, verbose_name='商品状态')),
            ],
            options={
                'verbose_name': ('商品表',),
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '商品类型表',
            },
        ),
        migrations.CreateModel(
            name='GroupApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('good_code', models.CharField(max_length=30, verbose_name='商品编码')),
                ('num', models.IntegerField(verbose_name='商品数量')),
                ('username', models.CharField(max_length=30, verbose_name='使用人')),
                ('position', models.CharField(max_length=100, verbose_name='所在地区')),
                ('phone', models.CharField(max_length=30, verbose_name='联系电话')),
                ('status', models.IntegerField(verbose_name='物资状态')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('position', models.CharField(max_length=100, verbose_name='所在地区')),
                ('phone', models.CharField(max_length=30, verbose_name='联系电话')),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('good_apply_id', models.IntegerField(verbose_name='物资id')),
                ('username', models.CharField(max_length=30, verbose_name='申请人')),
                ('reason_id', models.IntegerField(verbose_name='退回原因id')),
                ('position', models.CharField(max_length=100, verbose_name='退库地址')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('status', models.BooleanField(default=0, verbose_name='退库状态')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(max_length=20, verbose_name='退货原因')),
            ],
        ),
    ]
