# Generated by Django 2.2.6 on 2022-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapply',
            name='status',
            field=models.IntegerField(choices=[(0, '已退回'), (1, '在使用'), (2, '退回中')], verbose_name='物资状态'),
        ),
    ]
