# Generated by Django 2.2.6 on 2022-01-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapply',
            name='remarks',
            field=models.CharField(default='', max_length=255, verbose_name='备注'),
        ),
    ]
