# Generated by Django 2.2.6 on 2022-01-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0002_auto_20220113_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='status',
            field=models.BooleanField(choices=[(1, '已下架'), (2, '正常')], default=1, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='groupapply',
            name='status',
            field=models.IntegerField(choices=[(1, '已退回'), (2, '在使用'), (3, '退回中')], verbose_name='物资状态'),
        ),
    ]
