# Generated by Django 2.2.6 on 2022-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0003_auto_20220113_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='status',
            field=models.BooleanField(choices=[(0, '已下架'), (1, '正常')], default=1, verbose_name='商品状态'),
        ),
    ]
