# Generated by Django 2.2.6 on 2022-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0004_auto_20220113_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodtype',
            name='type_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='类型名称'),
        ),
    ]
