# Generated by Django 2.2.6 on 2022-01-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0004_auto_20220123_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地区'),
        ),
    ]
