# Generated by Django 2.2.6 on 2022-01-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0005_auto_20220124_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '购物车表', 'verbose_name_plural': '购物车表'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-update_time'], 'verbose_name': ('商品表',), 'verbose_name_plural': '商品表'},
        ),
        migrations.AlterModelOptions(
            name='goodtype',
            options={'verbose_name': '商品类型表', 'verbose_name_plural': '商品类型表'},
        ),
        migrations.AlterModelOptions(
            name='groupapply',
            options={'verbose_name': '部门所需物资表', 'verbose_name_plural': '部门所需物资表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '个人信息表', 'verbose_name_plural': '个人信息表'},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'verbose_name': '物资退回表', 'verbose_name_plural': '物资退回表'},
        ),
        migrations.AlterModelOptions(
            name='withdrawreason',
            options={'verbose_name': '退库原因表', 'verbose_name_plural': '退库原因表'},
        ),
    ]
