# Generated by Django 2.2.6 on 2022-01-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0005_auto_20220116_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapply',
            name='remarks',
            field=models.CharField(default='无', max_length=255, verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupapply',
            name='status',
            field=models.IntegerField(choices=[(1, '已退回'), (2, '在使用'), (3, '退回中'), (4, '购买中')], verbose_name='物资状态'),
        ),
    ]
