# Generated by Django 2.2.6 on 2022-01-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0006_auto_20220125_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapply',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='联系电话'),
        ),
    ]
