# Generated by Django 2.2.6 on 2022-03-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0008_auto_20220310_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='create_user',
            field=models.CharField(default='admin', max_length=120, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='cart',
            name='update_user',
            field=models.CharField(default='admin', max_length=120, verbose_name='更新用户'),
        ),
        migrations.AddField(
            model_name='good',
            name='create_user',
            field=models.CharField(default='admin', max_length=120, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='good',
            name='update_user',
            field=models.CharField(default='admin', max_length=120, verbose_name='更新用户'),
        ),
        migrations.AddField(
            model_name='groupapply',
            name='create_user',
            field=models.CharField(default='admin', max_length=120, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='groupapply',
            name='update_user',
            field=models.CharField(default='admin', max_length=120, verbose_name='更新用户'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='create_user',
            field=models.CharField(default='admin', max_length=120, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='update_user',
            field=models.CharField(default='admin', max_length=120, verbose_name='更新用户'),
        ),
    ]
