# Generated by Django 2.2.6 on 2022-03-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0011_auto_20220326_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='update_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='更新用户'),
        ),
        migrations.AlterField(
            model_name='good',
            name='create_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='good',
            name='update_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='更新用户'),
        ),
        migrations.AlterField(
            model_name='groupapply',
            name='create_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='groupapply',
            name='update_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='更新用户'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='create_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='update_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='更新用户'),
        ),
    ]
