# Generated by Django 2.2.6 on 2022-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0012_auto_20220326_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='所在组id'),
        ),
        migrations.AddField(
            model_name='good',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='所在组id'),
        ),
        migrations.AddField(
            model_name='goodtype',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='所在组id'),
        ),
        migrations.AddField(
            model_name='groupapply',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='所在组id'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='所在组id'),
        ),
        migrations.AddField(
            model_name='withdrawreason',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='所在组id'),
        ),
    ]
