# Generated by Django 2.2.6 on 2022-04-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_purchase', '0013_auto_20220401_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='组id'),
        ),
        migrations.AlterField(
            model_name='good',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='组id'),
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='组id'),
        ),
        migrations.AlterField(
            model_name='groupapply',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='组id'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='组id'),
        ),
        migrations.AlterField(
            model_name='withdrawreason',
            name='org_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='组id'),
        ),
    ]
