# Generated by Django 2.2.6 on 2022-01-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('good_code', models.CharField(max_length=30, verbose_name='物资编号')),
                ('good_name', models.CharField(max_length=50, verbose_name='物资名称')),
                ('num', models.IntegerField(verbose_name='申请数量')),
                ('require_date', models.DateField(verbose_name='期望领用日期')),
                ('reason', models.CharField(max_length=255, verbose_name='申请原因')),
                ('position', models.CharField(max_length=100, verbose_name='所在地区')),
                ('status', models.IntegerField(choices=[(0, '申请终止'), (1, '组长审核中'),
                                                        (2, '管理员审核中'), (3, '审核完成')], default=1, verbose_name='申请状态')),
                ('apply_user', models.CharField(max_length=30, verbose_name='申请人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(max_length=10, unique=True, verbose_name='地区代码')),
                ('name', models.CharField(max_length=20, verbose_name='地区名')),
                ('parent_code', models.CharField(max_length=10, null=True, verbose_name='上级地区代码')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('apply_id', models.IntegerField(verbose_name='申请物资id')),
                ('reviewer', models.CharField(max_length=30, verbose_name='审核人')),
                ('reviewer_identity', models.BooleanField(verbose_name='审核人身份')),
                ('result', models.BooleanField(verbose_name='审核结果')),
                ('reason', models.CharField(max_length=255, verbose_name='审核意见')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='秘书用户名')),
            ],
        ),
    ]
