# Generated by Django 2.2.6 on 2022-01-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.IntegerField(choices=[(1, '申请终止'), (2, '组长审核中'), (3, '管理员审核中'), (4, '审核完成')], default=1, verbose_name='申请状态'),
        ),
    ]
