# Generated by Django 2.2.6 on 2022-01-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0002_auto_20220113_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer_identity',
            field=models.BooleanField(choices=[(1, '组长'), (2, '秘书')], verbose_name='审核人身份'),
        ),
    ]
