# Generated by Django 2.2.6 on 2022-01-25 09:12

from django.db import migrations


def add_new_position_data(apps, schema_editor):
    Position = apps.get_model('good_apply', 'Position')
    position_list = [['001', '广东', '000'], ['002', '深圳', '001'], ['003', '上海', '000'], ['004', '成都', '000']]
    for position in position_list:
        obj = Position(position_code=position[0], name=position[1], parent_code=position[2])
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0003_auto_20220125_1550'),
    ]

    operations = [
        migrations.RunPython(add_new_position_data),
    ]
