# Generated by Django 2.2.6 on 2022-02-21 11:28

from django.db import migrations


def update_position_data(apps, schema_editor):
    Position = apps.get_model('good_apply', 'Position')
    position_objs = Position.objects.filter(parent_code='000')
    position_objs.update(parent_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0004_auto_20220125_1712'),
    ]

    operations = [
        migrations.RunPython(update_position_data),
    ]
