# Generated by Django 2.2.6 on 2022-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0005_auto_20220221_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.IntegerField(choices=[(0, '申请终止'), (1, '导员审核中'), (2, '管理员审核中'),
                                               (3, '审核完成')], default=1, verbose_name='申请状态'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_identity',
            field=models.IntegerField(choices=[(1, '导员'), (2, '秘书')], verbose_name='审核人身份'),
        ),
    ]
