# Generated by Django 2.2.6 on 2022-02-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0006_auto_20220221_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer_identity',
            field=models.IntegerField(choices=[(1, '导员'), (2, '管理员')], verbose_name='审核人身份'),
        ),
    ]
