# Generated by Django 2.2.6 on 2022-02-27 00:16

from django.db import migrations


def reset_position_data(apps, schema_editor):
    Position = apps.get_model('good_apply', 'Position')
    Position.objects.all().delete()
    position_list = [['001', '广东', None], ['002', '深圳', '001'], ['003', '广州', '001'], ['004', '东莞', '001'],
                     ['005', '湖北', None], ['006', '武汉', '005'], ['007', '黑龙江', None], ['008', '哈尔滨', '007']]
    bulk_create_list = list()
    for position in position_list:
        obj = Position(position_code=position[0], name=position[1], parent_code=position[2])
        bulk_create_list.append(obj)
    Position.objects.bulk_create(bulk_create_list)


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0007_auto_20220221_1456'),
    ]

    operations = [
        migrations.RunPython(reset_position_data),
    ]
