# Generated by Django 2.2.6 on 2022-03-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0009_auto_20220326_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='update_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='update_user',
        ),
    ]
