# Generated by Django 2.2.6 on 2022-03-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0011_auto_20220326_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='create_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='update_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='更新用户'),
        ),
        migrations.AlterField(
            model_name='review',
            name='create_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='创建用户'),
        ),
        migrations.AlterField(
            model_name='review',
            name='update_user',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='更新用户'),
        ),
    ]
