# Generated by Django 2.2.6 on 2022-04-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0014_auto_20220401_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.IntegerField(choices=[(0, '申请终止'), (1, '管理员审核中'),
                                               (2, '审核完成')], default=1, verbose_name='申请状态'),
        ),
    ]
