# Generated by Django 2.2.6 on 2022-04-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_apply', '0015_auto_20220401_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer_identity',
            field=models.IntegerField(choices=[(1, '管理员')], verbose_name='审核人身份'),
        ),
    ]
